### PR TITLE
fix: Add Skeleton and make warning conditional in Crypto-to-fiat compliance UI

### LINKED ISSUE #55: EasyInvoice - Fix Crypto-to-fiat bugs
# Problem(s)

1. Bad error message: https://github.com/RequestNetwork/easy-invoice/blob/8487193709253543837de2181944824b98cd3825/src/server/routers/compliance.ts#L53-L54
2. The compliance confirmation toast appears twice
3. Unhelpful Compliance form validation error. Appears as a 500 Internal Error instead of a zod error. Doesn't help user understand which field is wrong.
4. Investigate warnings like: `page-a6608841aa1107c9.js:1 Received postMessage from untrusted origin: https://easyinvoice.stage.request.network`
5. Should the compliance warning go away after KYC and the Agreement are both completed? Image
6. Crypto-to-fiat compliance status page flashes "Not Started". Recommend a suspense, skeleton, or loading indicator to avoid showing the user incorrect status. Don't display default values. Screen Recording: https://github.com/user-attachments/assets/486e9667-f619-4dfc-868d-3370e0cc9570 
7. EasyInvoice includes incoming webhook handlers for event names that don't exist in Request API. EasyInvoice expects Crypto-to-fiat webhook event names: settlement.initiated, settlement.failed, settlement.bounced, settlement.pending_internal_assessment, settlement.ongoing_checks , settlement.sending_fiat, settlement.fiat_sent

### PR DESCRIPTION
**Pull request by rodrigopavezi**
Fixes #55 issues: 5 and 6

## Summary by CodeRabbit

- **New Features**
	- Introduced a skeleton loader to visually indicate loading states in compliance-related components.
- **Enhancements**
	- Improved user feedback by displaying loading placeholders while compliance status is being fetched.
	- Updated compliance status display to support and reflect loading states.
- **Style**
	- Refined layout and spacing in the crypto-to-fiat conversion form for a cleaner appearance.

### CODE REVIEW

File: src/components/compliance-form.tsx [hunk 1]
```diff
@@ -240,11 +241,18 @@ export function ComplianceForm({ user }: { user: User }) {
...
+            </div>
+          ) : complianceData?.status.kycStatus !== "not_started" ||
+            complianceData?.status.agreementStatus !== "not_started" ? (
             <div className="flex flex-col gap-6 w-full">
               <div>
-                <ComplianceStatus status={complianceData?.status} />
+                <ComplianceStatus
+                  status={complianceData?.status}
+                  isLoading={isLoadingStatus}
+                />
```
Comment (MantisClone) [inline src/components/compliance-form.tsx:255]: This nested ternary is confusing to read. If you agree, consider refactoring.

**Review by MantisClone — APPROVED** [review]

File: src/components/compliance-form.tsx (hunk 1 above)
Comment (rodrigopavezi) [reply src/components/compliance-form.tsx:255]: It works
