### PR TITLE
Dark mode + UI fixes

### LINKED ISSUE #46: EasyInvoice - Dark Mode

### PR DESCRIPTION
**Pull request by mayur1377**
https://github.com/RequestNetwork/easy-invoice/issues/46 : add dark mode , a few snapshots below

Screenshot 2025-08-01 at 12 38 17 AM
Screenshot 2025-08-01 at 12 38 41 AM
Screenshot 2025-08-01 at 12 40 14 AM

## Summary by CodeRabbit

- New Features
  - System-aware dark mode with a visible theme toggle.
  - User menu adds a "Copy email" action.
  - Theme provider expanded to cover more UI for consistent theming.

- Style
  - Wide migration to semantic design tokens for colors, borders, and hover states.
  - Updated visuals for buttons, links, cards, tables, badges, tooltips, loaders, and empty states.
  - Standardized success/warning/destructive/muted/foreground styles across components.

### CODE REVIEW

**Comment by MantisClone** [comment]
Hello @mayur1377, thank you for submitting your first pull request to the easy-invoice repository. We value your contribution and encourage you to review our contribution guidelines to ensure your submission meets our standards. Please note that every merged PR is automatically enrolled in our Best PR Initiative, offering a chance to win $500 each quarter. Our team is available via [GitHub Discussions](https://github.com/orgs/RequestNetwork/discussions) or [Discord](https://request.network/discord) if you have any questions. Welcome aboard!

**Comment by MantisClone** [comment]
Thank you for your submission! As you prepare for the review process, please ensure that your PR title, description, and any linked issues fully comply with our contribution guidelines. A clear explanation of your changes and their context will help expedite the review process. Every merged PR is automatically entered into our Best PR Initiative, offering a chance to win $500 every quarter. We appreciate your attention to detail and look forward to reviewing your contribution!

File: src/components/direct-payout.tsx [hunk 1]
```diff
@@ -229,20 +233,22 @@ export function DirectPayment() {
...
+                        : "text-muted-foreground"
                     }`}
                   >
                     <div
                       className={`w-8 h-8 rounded-full border-2 flex items-center justify-center ${
                         currentStep >= 2
-                          ? "border-black bg-zinc-50"
-                          : "border-zinc-300"
+                          ? "border-foreground bg-muted"
+                          : "border-border"
```
Comment (bassgeta) [inline src/components/direct-payout.tsx:251]: Is it possible to rename border-border into border-primary or something? `border-border` is a bit funny :D

**Review by bassgeta — CHANGES_REQUESTED** [review]
Thank you for your contribution to Easy Invoice <3
Really good work, thanks for switching our tailwind variable names to something semantic instead of just using the colour names...

On top of the 3 things I commented on, I've noticed a pretty weird bug which happens only when loading the app the very first time:
image
Something gets mixed up and some components end up in their dark theme variant, while others do not.
Tried this out on multiple Chromium browsers and I can reproduce it constantly.

The error goes away after toggling the theme at least once.

Not sure what the solution could be, but maybe the theme switcher should check if theme isn't yet set, to just default to the light theme.

Other than that loving the dark mode look :sunglasses: 
image

Some more issues with dark mode:
1. Invoice me links
image
2. The alert modal's delete text is dark, should probably be white
image
3. The user popup is still white in dark mode
image
4. The `/invoices/:id` page is borked
image

And sadly, mandatory merge conflicts due to one of our huge PRs coming in, sorry about that :sweat_smile: 
After merging, do check the `/subscription-plans` route, there's a ton of added things there now.

After the UI issues and review comments are taken care of, I'll gladly drop an approval :100:

**Review by bassgeta — CHANGES_REQUESTED** [review]
Hey! Thanks for resolving the merge conflicts, sadly some new ones appeared :sweat_smile: 
Additionally, I can still reproduce all the bugs I've pointed out in my previous review, can we take care of those too? :pray: 
Feel free to gimme a shout if you need some help or pointers!

**Comment by mayur1377** [comment]
> Hey! Thanks for resolving the merge conflicts, sadly some new ones appeared 😅 Additionally, I can still reproduce all the bugs I've pointed out in my previous review, can we take care of those too? 🙏 Feel free to gimme a shout if you need some help or pointers!

it would be very much helpful if you could resolve the conflicts ^^

**Review by bassgeta — CHANGES_REQUESTED** [review]
Alright thanks a bunch for the updates! Just got around to checking this PR out again.

Let's go over the issues I've pointed out last time first:
1. Invoice me links are now correctly styled :heavy_check_mark: 
image
2. The delete modal from invoice me in now in light mode, probably not intended :heavy_multiplication_x: 
image
3.User popup is now in dark mode :heavy_check_mark: 
image
4. The `/invoices/:id` page now looks nice :heavy_check_mark: 
image

The dark mode blip doesn't happen to me anymore, nice job sorting that out!

There is one more issue similar to the blip we had before, but now it at least resolves itself.
When I load any page in dark mode initially, it shows up in a half light and half dark mode state, but resolves itself after all the data is filled in.

https://github.com/user-attachments/assets/d97e09bd-59f4-4aee-b391-aec8d40a72ad

Do you think you can solve this too? 
**Reproduction steps:** Just set your theme to dark and reload any page

Also needs a rebase, let me know if I can be of help there too :pray:

**Comment by mayur1377** [comment]
> When I load any page in dark mode initially, it shows up in a half light and half dark mode state, but resolves itself after all the data is filled in.



> > > Alright thanks a bunch for the updates! Just got around to checking this PR out again.
> > > Let's go over the issues I've pointed out last time first:
> > > 
> > > 1. Invoice me links are now correctly styled ✔️
> > > 
> > > image 2. The delete modal from invoice me in now in light mode, probably not intended ✖️ image 3.User popup is now in dark mode ✔️ image 4. The `/invoices/:id` page now looks nice ✔️ image
> > > The dark mode blip doesn't happen to me anymore, nice job sorting that out!
> > > There is one more issue similar to the blip we had before, but now it at least resolves itself. When I load any page in dark mode initially, it shows up in a half light and half dark mode state, but resolves itself after all the data is filled in.
> > > initial-load-dark-mode-2025-09-01_11.46.41.mp4
> > > Do you think you can solve this too? **Reproduction steps:** Just set your theme to dark and reload any page
> > > Also needs a rebase, let me know if I can be of help there too 🙏
> > 
> > 
> > hello , apologies but have been really busy in the past few weeks , kindly rebase and i will take a look!
> 
> Hey @mayur1377 , apologies that it took so long to rebase this, it's been a really busy couple of weeks. I've just pushed after resolving rebase conflicts. Let me know if you are able to take a look at the remaining issues, once the last few are solved, I will gladly approve and enjoy Easy Invoice in dark mode 😎

done , kindly take a look at it!!

**Review by bassgeta — APPROVED** [review]
Nice going, tried everything out and all the remaining issues seem to have been fixed :100: 
Approving and we can merge this PR when the CI passes :heavy_check_mark: 
Thanks for your contribution and your patience :heart:

**Review by bassgeta — CHANGES_REQUESTED** [review]
My bad, upon further review I've found another bug :sweat_smile: 
Navigating between pages doesn't work anymore, I am getting this error:
image

So error 1 is:
```
SES_UNCAUGHT_EXCEPTION: Error: Rendered more hooks than during the previous render.
```

And error 2 is:

```
Warning: Cannot update a component (`HotReload`) while rendering a different component (`Router`). To locate the bad setState() call inside `Router`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render Component Stack: 
    Router webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:207
    ErrorBoundaryHandler webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:113
    ErrorBoundary webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160
    AppRouter webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:585
    ServerRoot webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:112
    Root webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:117
[<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
```

it probably has something to do with you rendering different content until everything is loaded. This didn't happen in the previous version, so the culprit is in the latest commit.

**Review by bassgeta — CHANGES_REQUESTED** [review]
Alright, nice job! Everything works as intended now, navigation works and everything looks exactly as it should, good stuff :ok_hand: 

There is only one minor bug which can probably be fixed easily.
The `ModeToggle` component spits out a hydration error, and it also has one initial render issue - when dark mode is selected beforehand, upon refreshing the app the switcher toggles to light mode first and then immediately goes to dark mode.


https://github.com/user-attachments/assets/6c09c35c-68dd-48c9-a4ce-e507b91fb391

Since you've done a ton of work on this already, adding some kind of placeholder to `ModeToggle` until the component is mounted (like you have done with the background wrapper), is going to be enough.

Sorry to nag you for this one last fix :pray:

**Review by bassgeta — CHANGES_REQUESTED** [review]
Hey!
I'm still getting the switching error in the `ModeToggle` component.
1. Set your theme to dark
2. Refresh the page and observe that the toggler is initially in light mode and gets changed to dark mode later on

[Some official docs](https://github.com/pacocoursey/next-themes?tab=readme-ov-file#avoid-hydration-mismatch)

I think that what you can do for the `ModeToggle` is that if the component isn't mounted, just render an empty button for the time being (SSR and themes are hard :sweat_smile: )
```TSX
<Button
      variant="ghost"
      className="relative h-8 w-16 rounded-full bg-muted p-0 dark:bg-muted"
      aria-label="Toggle dark mode"
      disabled
    />
```

Or something that will fill the space accordingly.

**Review by bassgeta — APPROVED** [review]
Nice one :ok_hand: 
After running through the app, I can confirm that there are no more visual glitcches and that the theme toggler does in fact display as disabled if we have dark mode enabled system wide :100: 
Thanks for you hard work on this, now let's :shipit:
